version: '3.8'

services:
  postgres-turnoya:
    image: postgres:15
    container_name: turnoya-db
    environment:
      POSTGRES_DB: businessdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-business-data:/var/lib/postgresql/data
    networks:
      - turnoya-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turnoya"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-business-data:

networks:
  turnoya-network:
    driver: bridge